// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "rsamara_types.hpp"
#include <Rcpp.h>

using namespace Rcpp;

// rcpp_init_from_database_
XPtr < Context > rcpp_init_from_database_(Rcpp::String name);
RcppExport SEXP rsamara_rcpp_init_from_database_(SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type name(nameSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_init_from_database_(name));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_init_from_json_
XPtr < Context > rcpp_init_from_json_(Rcpp::String json);
RcppExport SEXP rsamara_rcpp_init_from_json_(SEXP jsonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type json(jsonSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_init_from_json_(json));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_init_from_dataframe_
XPtr < Context > rcpp_init_from_dataframe_(Rcpp::List data);
RcppExport SEXP rsamara_rcpp_init_from_dataframe_(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_init_from_dataframe_(data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_run_
List rcpp_run_(SEXP handle);
RcppExport SEXP rsamara_rcpp_run_(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type handle(handleSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_run_(handle));
    return rcpp_result_gen;
END_RCPP
}
