# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_init_from_database_ <- function(name) {
    .Call('rsamara_rcpp_init_from_database_', PACKAGE = 'rsamara', name)
}

rcpp_init_from_json_ <- function(json) {
    .Call('rsamara_rcpp_init_from_json_', PACKAGE = 'rsamara', json)
}

rcpp_init_from_dataframe_ <- function(data) {
    .Call('rsamara_rcpp_init_from_dataframe_', PACKAGE = 'rsamara', data)
}

rcpp_run_ <- function(handle) {
    .Call('rsamara_rcpp_run_', PACKAGE = 'rsamara', handle)
}

