# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DBSimulationParamsDF <- function(idsimulation) {
    .Call('rsamara_DBSimulationParamsDF', PACKAGE = 'rsamara', idsimulation)
}

DBSimulationMeteoDF <- function(idsimulation) {
    .Call('rsamara_DBSimulationMeteoDF', PACKAGE = 'rsamara', idsimulation)
}

DBSimulationIdDF <- function(idsimulation) {
    .Call('rsamara_DBSimulationIdDF', PACKAGE = 'rsamara', idsimulation)
}

DBSimpleSimulationParamsDF <- function(idsimulation) {
    .Call('rsamara_DBSimpleSimulationParamsDF', PACKAGE = 'rsamara', idsimulation)
}

DBVarietyDF <- function(idvariete) {
    .Call('rsamara_DBVarietyDF', PACKAGE = 'rsamara', idvariete)
}

DBStationDF <- function(codestation) {
    .Call('rsamara_DBStationDF', PACKAGE = 'rsamara', codestation)
}

DBPlotDF <- function(idparcelle) {
    .Call('rsamara_DBPlotDF', PACKAGE = 'rsamara', idparcelle)
}

DBItineraryDF <- function(iditinerairetechnique) {
    .Call('rsamara_DBItineraryDF', PACKAGE = 'rsamara', iditinerairetechnique)
}

DBMeteoDF <- function(codestation, beginDate, endDate) {
    .Call('rsamara_DBMeteoDF', PACKAGE = 'rsamara', codestation, beginDate, endDate)
}

runDB <- function(idsimulation) {
    .Call('rsamara_runDB', PACKAGE = 'rsamara', idsimulation)
}

run2DF <- function(params, meteo) {
    .Call('rsamara_run2DF', PACKAGE = 'rsamara', params, meteo)
}

runDF <- function(from_date, to_date, simulation, variety, plot, itinerary, station, meteo) {
    .Call('rsamara_runDF', PACKAGE = 'rsamara', from_date, to_date, simulation, variety, plot, itinerary, station, meteo)
}

